
on: [push, pull_request]
name: Test
jobs:
  build:

    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]
        include:
          - os: linux
            arch: arm64
          - os: linux
            arch: arm

    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build project
      run: go build -o main-${{ matrix.os }}-${{ matrix.arch }} main.go
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        
    - name: Upload snapshots
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: main-${{ matrix.os }}-${{ matrix.arch }}
        # Directory containing files to upload
        path: main-${{ matrix.os }}-${{ matrix.arch }}
        
    - name: Upload releases
      if: startsWith(github.ref, 'refs/tags/') # on tag
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: main-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
